# Generated by Django 5.2.3 on 2026-06-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_purchase_supplier_cart_cartitem_order_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseItems',
            new_name='PurchaseItem',
        ),
    ]
