# Generated by Django 5.2.3 on 2026-06-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_rename_purchaseitems_purchaseitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productspecification',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productspecification',
            old_name='template_id',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='purchase_id',
            new_name='purchase',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='specificationtemplate',
            old_name='category_id',
            new_name='category',
        ),
    ]
