# Generated by Django 5.2.3 on 2026-07-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_rename_product_id_cartitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
