CREATE OR REPLACE function get_stock(
    p_product_id IN NUMBER
)
RETURN NUMBER
AS
  V_STOCK NUMBER
BEGIN
    SELECT STOCK_QUANTITY INTO V_STOCK FROM STORE_PRODUCT WHERE ID = p_product_id;
    RETURN V_STOCK
END;
/

CREATE OR REPLACE function get_stock(
    p_product_id IN NUMBER
)
RETURN NUMBER
AS
  V_STOCK NUMBER
BEGIN
    SELECT STOCK_QUANTITY INTO V_STOCK FROM STORE_PRODUCT WHERE ID = p_product_id;
    RETURN V_STOCK
END;
/