CREATE OR REPLACE FUNCTION get_stock(
    p_product_id IN NUMBER
)
RETURN NUMBER
AS
  V_STOCK NUMBER;
BEGIN
    SELECT STOCK_QUANTITY INTO V_STOCK FROM STORE_PRODUCT WHERE ID = p_product_id;
    RETURN V_STOCK;
END;
/

CREATE OR REPLACE FUNCTION average_rating(
    p_product_id IN NUMBER
)
RETURN NUMBER
AS
  V_AVERAGE NUMBER;
BEGIN
    SELECT  AVG(NVL(RATING, 0)) INTO V_AVERAGE FROM STORE_REVIEW WHERE PRODUCT_ID = p_product_id;
    RETURN V_AVERAGE;
END;
/