SELECT
    P.ID,
    P.PRODUCT_NAME,
    C.CATEGORY_NAME,
    B.BRAND_NAME,
    P.PRICE,
    P.STOCK_QUANTITY
FROM STORE_PRODUCT P
JOIN STORE_CATEGORY C
    ON P.CATEGORY_ID = C.ID
JOIN STORE_BRAND B
    ON P.BRAND_ID = B.ID;