INSERT INTO STORE_CATEGORY (ID, CATEGORY_NAME, DESCRIPTION)
VALUES (1, 'Laptop', 'Laptops and notebooks');

INSERT INTO STORE_CATEGORY (ID, CATEGORY_NAME, DESCRIPTION)
VALUES (2, 'Desktop', 'Desktop computers');

INSERT INTO STORE_BRAND (ID, BRAND_NAME, DESCRIPTION)
VALUES (1, 'HP', 'HP Inc.');

INSERT INTO STORE_BRAND (ID, BRAND_NAME, DESCRIPTION)
VALUES (2, 'Dell', 'Dell Technologies');

INSERT INTO STORE_BRAND (ID, BRAND_NAME, DESCRIPTION)
VALUES (3, 'Lenovo', 'Lenovo Group');

INSERT INTO STORE_SUPPLIER
(ID, SUPPLIER_NAME, PHONE_NO, EMAIL, ADDRESS)
VALUES
(
1,
'Tech Distribution Ltd.',
'01712345678',
'techdist@gmail.com',
'Dhaka, Bangladesh'
);

INSERT INTO STORE_PRODUCT
(ID, CATEGORY_ID, BRAND_ID, PRODUCT_NAME,
PRICE, STOCK_QUANTITY, DESCRIPTION, IMAGE, "DATE")
VALUES
(
1,
1,
1,
'HP Victus 15',
85000,
20,
'Gaming Laptop',
'images/hp.jpg',
SYSTIMESTAMP
);

INSERT INTO STORE_PRODUCT
(ID, CATEGORY_ID, BRAND_ID, PRODUCT_NAME,
PRICE, STOCK_QUANTITY, DESCRIPTION, IMAGE, "DATE")
VALUES
(
2,
1,
2,
'Dell Inspiron 15',
72000,
15,
'Office Laptop',
'images/dell.jpg',
SYSTIMESTAMP
);

INSERT INTO STORE_PRODUCT
(ID, CATEGORY_ID, BRAND_ID, PRODUCT_NAME,
PRICE, STOCK_QUANTITY, DESCRIPTION, IMAGE, "DATE")
VALUES
(
3,
1,
3,
'Lenovo LOQ',
99000,
10,
'Gaming Laptop',
'images/loq.jpg',
SYSTIMESTAMP
);

INSERT INTO STORE_PURCHASE
(ID, SUPPLIER_ID, "DATE", AMOUNT)
VALUES
(
1,
1,
SYSTIMESTAMP,
350000
);

INSERT INTO STORE_PURCHASEITEM
(ID, PURCHASE_ID, PRODUCT_ID, QUANTITY, COST)
VALUES
(
1,
1,
1,
5,
80000
);

INSERT INTO STORE_ORDER
(ID, USER_ID, "DATE", AMOUNT, STATUS)
VALUES
(
1,
1,
SYSTIMESTAMP,
85000,
'Pending'
);

INSERT INTO STORE_ORDERITEM
(ID, ORDER_ID, PRODUCT_ID, QUANTITY, PRICE)
VALUES
(
1,
1,
1,
3,
85000
);

INSERT INTO STORE_REVIEW
(ID, USER_ID, PRODUCT_ID, RATING, "COMMENT", "DATE")
VALUES
(
1,
1,
1,
5,
'Excellent gaming performance.',
SYSTIMESTAMP
);

INSERT INTO STORE_REVIEW
(ID, USER_ID, PRODUCT_ID, RATING, "COMMENT", "DATE")
VALUES
(
2,
1,
1,
4,
'Good battery backup.',
SYSTIMESTAMP
);