CREATE OR REPLACE TRIGGER auto_update_stock
AFTER INSERT ON STORE_PURCHASEITEM
FOR EACH ROW
BEGIN
    UPDATE STORE_PRODUCT
    SET STOCK_QUANTITY = STOCK_QUANTITY + :NEW.QUANTITY
    WHERE ID = :NEW.PRODUCT_ID;
END;
/

CREATE OR REPLACE TRIGGER prevent_or_reduce_stock
BEFORE INSERT ON STORE_ORDERITEM
FOR EACH ROW
DECLARE
    V_STOCK NUMBER;
BEGIN
    SELECT STOCK_QUANTITY INTO V_STOCK FROM STORE_PRODUCT WHERE ID = :NEW.PRODUCT_ID;
    IF :NEW.QUANTITY <= 0 THEN
    RAISE_APPLICATION_ERROR(
        -20002,
        'Quantity must be greater than zero.'
    );
    ELSIF :NEW.QUANTITY > V_STOCK THEN
    RAISE_APPLICATION_ERROR(
        -20001,
        'Insufficient stock.'
    );
    ELSE
    UPDATE STORE_PRODUCT
    SET STOCK_QUANTITY = STOCK_QUANTITY - :NEW.QUANTITY
    WHERE ID = :NEW.PRODUCT_ID;
    END IF;
END;
/